version: "3"

tasks:
  build-image:
    desc: Build Docker image
    cmds:
      - docker build -t catgirldownloader-packager .

  build-packages:
    desc: Build packages (no Flatpak)
    deps: [build-image]
    cmds:
      - docker run --rm -v "{{.USER_WORKING_DIR}}":/workspace catgirldownloader-packager

  build-packages-flatpak:
    desc: Build packages in Docker and Flatpak on host
    deps: [build-packages]
    cmds:
      - mkdir -p build
      - flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      - flatpak --user install -y org.gnome.Platform/x86_64/49 org.gnome.Sdk/x86_64/49
      - rm -rf .flatpak-builder/ flatpak-app/
      - flatpak-builder --disable-rofiles-fuse --install --user --force-clean flatpak-app moe.nyarchlinux.catgirldownloader.json
      - flatpak build-bundle ~/.local/share/flatpak/repo build/catgirldownloader.flatpak moe.nyarchlinux.catgirldownloader

  build:
    desc: Alias for build-packages
    deps: [build-packages]

  clean:
    desc: Remove local artifacts
    cmds:
      - rm -rf .flatpak-builder/ .local/ build/
